export const types = {
   SEARCH:"SEARCH",
   FILTER_CATEGORY: 'FILTER_CATEGORY',
   FILTER_BRAND: 'FILTER_BRAND',
   FILTER_ITEMS: 'FILTER_ITEMS',
   SELECT_CATEGORY: 'SELECT_CATEGORY',
   SELECT_BRAND: 'SELECT_BRAND',
   CLEAR_CATEGORIES: 'CLEAR_CATEGORIES',
   CLEAR_BRANDS:'CLEAR_BRANDS',
   SET_PRICE_RANGE: 'SET_PRICE_RANGE',
   SET_QUERY:'SET_QUERY',
   SET_RATING_RANGE:'SET_RATING_RANGE'
}
